# 100 NumPy Exercises

A graded set of practice problems for building NumPy fluency.

This notebook contains **100 NumPy practice exercises**, ordered roughly from easy to hard and marked with a difficulty rating:

- ★☆☆ = easy
- ★★☆ = medium
- ★★★ = hard

Each question has an empty code cell below it for you to write your solution. **No answers are provided** — look things up in the [NumPy documentation](https://numpy.org/doc/stable/) when you get stuck, that's part of the practice.

Run the setup cell below once before starting.

In [1]:
import numpy as np
np.random.seed(42)  # for reproducibility where randomness is used

#### 1. Import NumPy under the alias `np` and print its version. (★☆☆)

In [2]:
import numpy as np

#### 2. Create a 1D NumPy array containing the integers 0 through 9. (★☆☆)

In [3]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 3. Create a null (all-zero) vector of size 10. (★☆☆)

In [4]:
zeroes = np.zeros(10)
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. Create a null vector of size 10, but set the fifth value to 1. (★☆☆)

In [5]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 5. Create a vector with values ranging from 10 to 49. (★☆☆)

In [6]:
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 6. Reverse a vector (first element becomes last). (★☆☆)

In [7]:
arr = np.array(np.arange(1,6))
rev= arr[::-1]
print(rev)

[5 4 3 2 1]


#### 7. Create a 3x3 matrix with values ranging from 0 to 8. (★☆☆)

In [12]:
matrix = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


#### 8. Find the indices of all non-zero elements in the array [1,2,0,0,4,0]. (★☆☆)

In [13]:
arr = [1,2,0,0,4,0]
index = np.nonzero(arr)
print(index)

(array([0, 1, 4]),)


#### 9. Create a 3x3 identity matrix. (★☆☆)

#### 10. Create a 3x3x3 array with random values. (★☆☆)

#### 11. Create a 10x10 array with random values and find the minimum and maximum values. (★☆☆)

#### 12. Create a random vector of size 30 and find its mean value. (★☆☆)

#### 13. Create a 2D array with 1 on the border and 0 inside (size 5x5). (★★☆)

#### 14. Add a border of zeros around an existing 2D array. (★★☆)

#### 15. Explain and demonstrate the result of `0 * np.nan`, `np.nan == np.nan`, and `np.inf > np.nan`. (★★☆)

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal. (★★☆)

#### 17. Create an 8x8 matrix and fill it with a checkerboard pattern of 0s and 1s. (★★☆)

#### 18. Given a shape (6,7,8), find the index (x,y,z) of the 100th element using `np.unravel_index`. (★★☆)

#### 19. Create a checkerboard 8x8 matrix using the `tile` function. (★★☆)

#### 20. Normalize a 5x5 random matrix (subtract mean, divide by std). (★★☆)

#### 21. Create a custom dtype that describes a color as four unsigned bytes (RGBA). (★★★)

#### 22. Multiply a 5x3 matrix by a 3x2 matrix using real matrix multiplication. (★★☆)

#### 23. Given a 1D array, negate all elements that are between 3 and 8, in place. (★★☆)

#### 24. Explain the output of `sum(range(5), -1)` versus `np.sum(range(5), -1)`. (★★☆)

#### 25. Given an integer vector Z, determine which of these expressions are legal: `Z**Z`, `2 << Z >> 2`, `Z <- Z`, `1j*Z`, `Z/1/1`, `Z<Z>Z`. (★★★)

#### 26. Evaluate the results of `np.array(0) / np.array(0)`, `np.array(0) // np.array(0)`, and `np.array([np.nan]).astype(int).astype(float)`. (★★★)

#### 27. Round a float array away from zero (e.g., -0.5 rounds to -1, not 0). (★★☆)

#### 28. Find the common values between two random integer arrays. (★★☆)

#### 29. Suppress all NumPy warnings temporarily (using a context manager). (★★☆)

#### 30. Check whether `np.sqrt(-1) == np.emath.sqrt(-1)` and explain why. (★★★)

#### 31. Get yesterday's, today's, and tomorrow's dates using `np.datetime64`. (★★☆)

#### 32. Generate an array of all dates for the month of July 2026. (★★☆)

#### 33. Compute `((A+B)*(-A/2))` in place for two arrays A and B without creating a copy. (★★★)

#### 34. Extract the integer part of a random positive array using 4 different methods. (★★☆)

#### 35. Create a 5x5 matrix where each row contains values 0 to 4. (★☆☆)

#### 36. Create a generator function producing 10 integers, then build an array from it. (★★☆)

#### 37. Create a vector of size 10 with values evenly spaced between 0 and 1 (excluding both endpoints). (★★☆)

#### 38. Create a random vector of size 10 and sort it. (★☆☆)

#### 39. Sum a small array faster than `np.sum` using an alternative method. (★★☆)

#### 40. Check if two random arrays are element-wise equal. (★☆☆)

#### 41. Make a NumPy array immutable (read-only). (★★☆)

#### 42. Convert a 10x2 matrix of Cartesian coordinates to polar coordinates. (★★☆)

#### 43. Create a random vector of size 10 and replace the maximum value with 0. (★☆☆)

#### 44. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area. (★★★)

#### 45. Given two arrays X and Y, construct the Cauchy matrix C where `C[i,j] = 1/(X[i]-Y[j])`. (★★★)

#### 46. Print the minimum and maximum representable values for each NumPy scalar integer and float type. (★★☆)

#### 47. Print all the values of an array without truncation (change print options). (★☆☆)

#### 48. Find the closest value to a given scalar in a vector. (★★☆)

#### 49. Create a structured array representing a position (x,y) and color (r,g,b) for a set of points. (★★★)

#### 50. Given a random vector representing coordinates, find point-by-point distances. (★★★)

#### 51. Convert a float (32-bit) array into an integer (32-bit) array in place. (★★☆)

#### 52. Read a text file with irregular numbers of columns per row (missing values) into an array. (★★★)

#### 53. Enumerate both the index and value of every element in a NumPy array. (★★☆)

#### 54. Build a generic 2D Gaussian-like array centered at the middle. (★★☆)

#### 55. Randomly place p elements in a 2D array of shape (n,n). (★★☆)

#### 56. Subtract the mean of each row of a matrix. (★★☆)

#### 57. Sort an array by the nth column. (★★☆)

#### 58. Determine if a given 2D array has null (all-zero) columns. (★★☆)

#### 59. Find the nearest value to a given number in an array. (★☆☆)

#### 60. Compute the sum of an array by iterating using `np.nditer`. (★★☆)

#### 61. Create a symmetric array class where `A[i,j] == A[j,i]` is enforced automatically. (★★★)

#### 62. Given a set of matrices, compute the sum of the matrix products (batch matrix multiplication). (★★★)

#### 63. Given a 16x16 array, compute the sum over blocks of 4x4 elements. (★★★)

#### 64. Implement the Game of Life using NumPy array operations. (★★★)

#### 65. Find the n largest values in an array. (★★☆)

#### 66. Given an arbitrary number of vectors, build the Cartesian product (all combinations of values). (★★★)

#### 67. Create a NumPy array from a regular Python list of tuples/records. (★☆☆)

#### 68. Build a rank-1 matrix (outer product) from two vectors. (★☆☆)

#### 69. Given a two-dimensional array, extract a row where the sum of the row is maximal. (★★☆)

#### 70. Find the row of a matrix that is closest to a given vector, using Euclidean distance. (★★☆)

#### 71. Compute the moving average of a 1D array over a window of size 3. (★★☆)

#### 72. Build a 2D array from a 1D array where each row is a shifted window (sliding window view). (★★★)

#### 73. Negate a boolean array, or change the sign of a float array, in place. (★☆☆)

#### 74. Compute the distance from each point in a set of points to a line defined by two points. (★★★)

#### 75. Compute distances from each point in a set to each of several lines. (★★★)

#### 76. Extract a fixed-size subpart of an array, centered on a given element, padding with a fill value if out of bounds. (★★★)

#### 77. Given an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], generate an array R such that each element is a sliding window of size 4. (★★★)

#### 78. Compute the rank of a matrix using SVD. (★★☆)

#### 79. Find the most frequent value in an array, ignoring a specific 'ignore' value. (★★☆)

#### 80. Extract all contiguous 3x3 patches from a random 10x10x3 (RGB-like) array. (★★★)

#### 81. Create a rank-4 tensor with shape (2,2,2,2) and compute the sum over the last two axes. (★★☆)

#### 82. Given a 1D vector D and a vector S of the same size with subgroup indices, compute the means of D grouped by the subgroups in S. (★★★)

#### 83. Compute the diagonal of a dot product of two matrices without computing the full dot product. (★★★)

#### 84. Given a vector [1,2,3,4,5], build a new vector with 3 consecutive zeros interleaved between each value. (★★☆)

#### 85. Multiply a 5x5x3 array by a 5x5 2D array (broadcast an extra dimension). (★★☆)

#### 86. Swap two rows of a 2D array. (★☆☆)

#### 87. Given a set of 10 line segments (start/end point pairs), find the set of unique segments composing all lines. (★★★)

#### 88. Given a set of unique line segments, compute a bincount-compatible array from segment indices. (★★★)

#### 89. Given a random array, find the row that is most similar to a specific target row, using cosine similarity computed with NumPy. (★★★)

#### 90. Create a 2D array subclass such that `Z[i,j] == Z[j,i]` is always enforced automatically. (★★★)

#### 91. Given a 16x16 array, compute a block-sum reduction to a 4x4 array (sum over 4x4 blocks). (★★★)

#### 92. Implement one step of Conway's Game of Life on an 8x8 boolean board using array operations. (★★★)

#### 93. Get the n largest values of an array using `np.argpartition` instead of a full sort. (★★☆)

#### 94. Build a 2D sliding-window view of a 1D array of window size 3 using `np.lib.stride_tricks.sliding_window_view`. (★★★)

#### 95. Given a sorted bincount-style array C, reconstruct an array A such that `np.bincount(A) == C`. (★★★)

#### 96. Compute a moving average of an array using `np.convolve` with a uniform kernel. (★★☆)

#### 97. Print all the values of a very large array without triggering NumPy's summarization/truncation. (★☆☆)

#### 98. Consider a set of 10 triplets describing triangle vertex indices; find the set of unique edges (line segments) across all triangles. (★★★)

#### 99. Given two arrays of shape (100,2) representing points, compute the pairwise Euclidean distance matrix between them. (★★☆)

#### 100. Create a function that takes an integer n and returns an nxn matrix with a checkerboard pattern using `np.indices`. (★★☆)