# NumPy Guide

A hands-on, self-contained guide to NumPy. Each section has a short explanation, one worked example (with code shown), and several **practice tasks** for you to complete in the empty cells. No answers are included — use the linked docs when stuck.

In [2]:
import numpy as np
np.random.seed(0)
print(np.__version__)

2.4.3


## 1. Arrays, Shapes & Dtypes

[NumPy absolute basics](https://numpy.org/doc/stable/user/absolute_beginners.html)

NumPy arrays are the core data structure for numerical computing in Python. Unlike Python lists, they are fixed-type and support fast vectorized operations.

**Worked example:** create an array and inspect its shape/dtype.

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('shape:', arr.shape)
print('dtype:', arr.dtype)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
dtype: int64


**Practice 1.1** (★☆☆) Create a 4x4 array of random integers between 0 and 100. Print its shape, dtype, and total number of elements.

**Practice 1.2** (★☆☆) Create an array of 20 evenly spaced numbers between 0 and 5 using `np.linspace`.

**Practice 1.3** (★☆☆) Create a 3x3 identity matrix and a 3x3 matrix of all ones, then add them together.

**Practice 1.4** (★★☆) Convert a Python list of lists (uneven row lengths not allowed) into a NumPy array, then reshape it into a different valid shape.

## 2. Indexing, Slicing & Boolean Masks

[Indexing docs](https://numpy.org/doc/stable/user/basics.indexing.html)

NumPy supports slicing like Python lists, but also fancy indexing and boolean masks that let you select or modify elements based on conditions, without loops.

**Worked example:** select and modify elements with a boolean mask.

In [ ]:
# v = np.arange(10)
# mask = v % 2 == 0
# print(v[mask])
# v[mask] = -1
# print(v)

[0 2 4 6 8]
[-1  1 -1  3 -1  5 -1  7 -1  9]


**Practice 2.1** (★☆☆) Given a 1D array of 15 random integers, select all values greater than the array's mean.

**Practice 2.2** (★★☆) Given a 5x5 array of random floats, replace every value less than 0.5 with 0, using boolean indexing (no loops).

**Practice 2.3** (★★☆) Given a 2D array, extract every other row and every other column using slicing.

**Practice 2.4** (★★★) Given an array of shape (10,), use fancy indexing to construct a new array that repeats index [0,2,4] three times each, in order (e.g. 0,0,0,2,2,2,4,4,4).

## 3. Broadcasting & Vectorized Operations

[Broadcasting docs](https://numpy.org/doc/stable/user/basics.broadcasting.html)

Broadcasting lets NumPy apply operations between arrays of different (but compatible) shapes without writing explicit loops.

**Worked example:** subtract the column mean from each column of a matrix.

In [ ]:
m = np.random.rand(4, 3)
col_means = m.mean(axis=0)
centered = m - col_means
print(centered.mean(axis=0).round(6))

**Practice 3.1** (★☆☆) Given a 5x5 matrix, subtract the row mean from each row (not the column mean).

**Practice 3.2** (★★☆) Given two vectors of length 4 and 6, use broadcasting to build a 4x6 outer-sum matrix where `M[i,j] = a[i] + b[j]`.

**Practice 3.3** (★★☆) Normalize a 2D array so every row sums to 1, using broadcasting.

**Practice 3.4** (★★★) Given an array of 3D points (shape N x 3), compute the full pairwise Euclidean distance matrix (N x N) using only broadcasting and vectorized operations (no loops).

## 4. Aggregation, Sorting & Statistics

[Statistics docs](https://numpy.org/doc/stable/reference/routines.statistics.html)

NumPy provides fast reductions (sum, mean, std, min, max) along any axis, plus sorting and searching utilities.

**Worked example:** compute per-column statistics.

In [ ]:
data = np.random.randn(100, 3)
print('mean:', data.mean(axis=0))
print('std:', data.std(axis=0))
print('max:', data.max(axis=0))

**Practice 4.1** (★☆☆) Given a random 1D array of 50 integers, find the 5 largest values without fully sorting the array (hint: `np.argpartition`).

**Practice 4.2** (★★☆) Given a 2D array, sort each row independently, then sort the rows themselves by their first column value.

**Practice 4.3** (★★☆) Compute a 5-element moving average of a 1D array of length 30 using `np.convolve`.

**Practice 4.4** (★★★) Given a 1D array of group labels and a same-length array of values, compute the mean value per group without using Pandas (hint: `np.unique` with `return_inverse`, or `np.bincount`).

## 5. Linear Algebra

[Linear algebra docs](https://numpy.org/doc/stable/reference/routines.linalg.html)

`numpy.linalg` provides matrix decompositions, determinants, inverses, eigenvalues, and more.

**Worked example:** solve a linear system Ax = b.

In [ ]:
A = np.array([[3, 1], [1, 2]], dtype=float)
b = np.array([9, 8], dtype=float)
x = np.linalg.solve(A, b)
print(x)

**Practice 5.1** (★★☆) Create two 3x3 matrices and compute their matrix product two different ways (`@` operator and `np.dot`).

**Practice 5.2** (★★☆) Compute the determinant and inverse of a random 4x4 matrix, then verify `A @ A_inv` is approximately the identity matrix.

**Practice 5.3** (★★★) Compute the rank of a matrix using `np.linalg.svd` (rather than `np.linalg.matrix_rank`).

## 6. Random Sampling, Dates & Structured Arrays

[Random sampling docs](https://numpy.org/doc/stable/reference/random/index.html)

NumPy's random module (via `np.random.default_rng()`) supports many distributions, and NumPy also has native datetime and structured-array support.

**Worked example:** sample from a normal distribution with a reproducible generator.

In [ ]:
rng = np.random.default_rng(42)
sample = rng.normal(loc=0, scale=1, size=10)
print(sample.round(3))

**Practice 6.1** (★☆☆) Using `np.random.default_rng`, generate 1000 samples from a uniform distribution between -1 and 1, then check what fraction are positive.

**Practice 6.2** (★★☆) Create an array of all dates in the month of July 2026 using `np.arange` with `dtype='datetime64[D]'`.

**Practice 6.3** (★★★) Create a structured array with fields `name` (string), `age` (int), and `score` (float) for 5 people, then sort the array by `score` descending.

---

### Where to go next

- For deliberate, exhaustive drilling across all difficulty levels, use the companion notebook: **100 NumPy Exercises**.
- [NumPy documentation](https://numpy.org/doc/stable/)
- [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)